apiVersion: v1
kind: Namespace
metadata:
  name: beam

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: beam-operator
  namespace: beam

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: beam-operator-role
rules:
  - apiGroups: ["batch", ""]
    resources: ["jobs","pods","pods/log","configmaps","secrets"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["beam.sordonez.com"]
    resources: ["beamdesigns","beamdesigns/status"]
    verbs: ["get","list","watch","create","update","patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: beam-operator-binding
subjects:
  - kind: ServiceAccount
    name: beam-operator
    namespace: beam
roleRef:
  kind: ClusterRole
  name: beam-operator-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beam-operator
  namespace: beam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beam-operator
  template:
    metadata:
      labels:
        app: beam-operator
    spec:
      serviceAccountName: beam-operator
      containers:
        - name: operator
          image: sjord01/beam-operator:0.1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: "INFO"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10